window.SL_CATALOG = (function () {

  var film = [
    { id:"film_vertigo_1958", title:"Vertigo", type:"Film", year:1958 },
    { id:"film_psycho_1960", title:"Psycho", type:"Film", year:1960 },
    { id:"film_jaws_1975", title:"Jaws", type:"Film", year:1975 },
    { id:"film_star_wars_1977", title:"Star Wars", type:"Film", year:1977 },
    { id:"film_godfather_1972", title:"The Godfather", type:"Film", year:1972 },
    { id:"film_godfather_2_1974", title:"The Godfather Part II", type:"Film", year:1974 },
    { id:"film_raiders_1981", title:"Raiders of the Lost Ark", type:"Film", year:1981 },
    { id:"film_et_1982", title:"E.T. the Extra-Terrestrial", type:"Film", year:1982 },
    { id:"film_back_future_1985", title:"Back to the Future", type:"Film", year:1985 },
    { id:"film_breakfast_club_1985", title:"The Breakfast Club", type:"Film", year:1985 },
    { id:"film_die_hard_1988", title:"Die Hard", type:"Film", year:1988 },
    { id:"film_ferris_bueller_1986", title:"Ferris Bueller’s Day Off", type:"Film", year:1986 },
    { id:"film_terminator_2_1991", title:"Terminator 2: Judgment Day", type:"Film", year:1991 },
    { id:"film_jurassic_park_1993", title:"Jurassic Park (Film)", type:"Film", year:1993 },
    { id:"film_pulp_fiction_1994", title:"Pulp Fiction", type:"Film", year:1994 },
    { id:"film_forrest_gump_1994", title:"Forrest Gump", type:"Film", year:1994 },
    { id:"film_fight_club_1999", title:"Fight Club", type:"Film", year:1999 },
    { id:"film_matrix_1999", title:"The Matrix", type:"Film", year:1999 },
    { id:"film_sixth_sense_1999", title:"The Sixth Sense", type:"Film", year:1999 },
    { id:"film_gladiator_2000", title:"Gladiator", type:"Film", year:2000 },
    { id:"film_lotr_fellowship_2001", title:"The Lord of the Rings: The Fellowship of the Ring", type:"Film", year:2001 },
    { id:"film_lotr_two_towers_2002", title:"The Lord of the Rings: The Two Towers", type:"Film", year:2002 },
    { id:"film_lotr_return_2003", title:"The Lord of the Rings: The Return of the King", type:"Film", year:2003 },
    { id:"film_dark_knight_2008", title:"The Dark Knight", type:"Film", year:2008 },
    { id:"film_avatar_2009", title:"Avatar", type:"Film", year:2009 },
    { id:"film_inception_2010", title:"Inception", type:"Film", year:2010 },
    { id:"film_social_network_2010", title:"The Social Network", type:"Film", year:2010 },
    { id:"film_interstellar_2014", title:"Interstellar", type:"Film", year:2014 },
    { id:"film_mad_max_fury_2015", title:"Mad Max: Fury Road", type:"Film", year:2015 },
    { id:"film_get_out_2017", title:"Get Out", type:"Film", year:2017 },
    { id:"film_parasite_2019", title:"Parasite", type:"Film", year:2019 },
    { id:"film_dune_2021", title:"Dune (Film)", type:"Film", year:2021 },
    { id:"film_top_gun_maverick_2022", title:"Top Gun: Maverick", type:"Film", year:2022 }
  ];

  var tv = [
    { id:"tv_i_love_lucy_1951", title:"I Love Lucy", type:"TV", year:1951 },
    { id:"tv_twilight_zone_1959", title:"The Twilight Zone", type:"TV", year:1959 },
    { id:"tv_mash_1972", title:"M*A*S*H", type:"TV", year:1972 },
    { id:"tv_cheers_1982", title:"Cheers", type:"TV", year:1982 },
    { id:"tv_seinfeld_1989", title:"Seinfeld", type:"TV", year:1989 },
    { id:"tv_friends_1994", title:"Friends", type:"TV", year:1994 },
    { id:"tv_x_files_1993", title:"The X-Files", type:"TV", year:1993 },
    { id:"tv_sopranos_1999", title:"The Sopranos", type:"TV", year:1999 },
    { id:"tv_west_wing_1999", title:"The West Wing", type:"TV", year:1999 },
    { id:"tv_lost_2004", title:"Lost", type:"TV", year:2004 },
    { id:"tv_office_us_2005", title:"The Office (US)", type:"TV", year:2005 },
    { id:"tv_grey_anatomy_2005", title:"Grey’s Anatomy", type:"TV", year:2005 },
    { id:"tv_breaking_bad_2008", title:"Breaking Bad", type:"TV", year:2008 },
    { id:"tv_mad_men_2007", title:"Mad Men", type:"TV", year:2007 },
    { id:"tv_game_thrones_2011", title:"Game of Thrones", type:"TV", year:2011 },
    { id:"tv_walking_dead_2010", title:"The Walking Dead", type:"TV", year:2010 },
    { id:"tv_stranger_things_2016", title:"Stranger Things", type:"TV", year:2016 },
    { id:"tv_handmaids_tale_2017", title:"The Handmaid’s Tale", type:"TV", year:2017 },
    { id:"tv_succession_2018", title:"Succession", type:"TV", year:2018 },
    { id:"tv_last_of_us_2023", title:"The Last of Us", type:"TV", year:2023 }
  ];

  var book = [
    { id:"book_1984_orwell_1949", title:"1984", type:"Book", year:1949 },
    { id:"book_catcher_rye_1951", title:"The Catcher in the Rye", type:"Book", year:1951 },
    { id:"book_lord_flies_1954", title:"Lord of the Flies", type:"Book", year:1954 },
    { id:"book_hobbit_1937", title:"The Hobbit", type:"Book", year:1937 },
    { id:"book_to_kill_mockingbird_1960", title:"To Kill a Mockingbird", type:"Book", year:1960 },
    { id:"book_dune_1965", title:"Dune (Book)", type:"Book", year:1965 },
    { id:"book_godfather_1969", title:"The Godfather", type:"Book", year:1969 },
    { id:"book_shining_1977", title:"The Shining", type:"Book", year:1977 },
    { id:"book_hitchhiker_1979", title:"The Hitchhiker’s Guide to the Galaxy", type:"Book", year:1979 },
    { id:"book_handmaids_tale_1985", title:"The Handmaid’s Tale (Book)", type:"Book", year:1985 },
    { id:"book_it_1986", title:"It", type:"Book", year:1986 },
    { id:"book_harry_potter_1997", title:"Harry Potter and the Philosopher’s Stone", type:"Book", year:1997 },
    { id:"book_girl_dragon_tattoo_2005", title:"The Girl with the Dragon Tattoo", type:"Book", year:2005 },
    { id:"book_hunger_games_2008", title:"The Hunger Games", type:"Book", year:2008 },
    { id:"book_gone_girl_2012", title:"Gone Girl (Book)", type:"Book", year:2012 }
  ,
    { id:"film_clueless_1995", title:"Clueless", type:"Film", year:1995 },
    { id:"film_when_harry_met_sally_1989", title:"When Harry Met Sally", type:"Film", year:1989 },
    { id:"film_pretty_woman_1990", title:"Pretty Woman", type:"Film", year:1990 },
    { id:"film_notting_hill_1999", title:"Notting Hill", type:"Film", year:1999 },
    { id:"film_princess_bride_1987", title:"The Princess Bride", type:"Film", year:1987 },
    { id:"film_legally_blonde_2001", title:"Legally Blonde", type:"Film", year:2001 },
    { id:"film_mean_girls_2004", title:"Mean Girls", type:"Film", year:2004 },
    { id:"film_little_miss_sunshine_2006", title:"Little Miss Sunshine", type:"Film", year:2006 },
    { id:"film_pride_prejudice_2005", title:"Pride & Prejudice", type:"Film", year:2005 },
    { id:"film_lady_bird_2017", title:"Lady Bird", type:"Film", year:2017 },
    { id:"film_hidden_figures_2016", title:"Hidden Figures", type:"Film", year:2016 },
    { id:"film_a_star_is_born_2018", title:"A Star Is Born", type:"Film", year:2018 },
    { id:"film_barbie_2023", title:"Barbie", type:"Film", year:2023 },
    { id:"film_alien_1979", title:"Alien", type:"Film", year:1979 },
    { id:"film_blade_runner_1982", title:"Blade Runner", type:"Film", year:1982 },
    { id:"film_rocky_1976", title:"Rocky", type:"Film", year:1976 },
    { id:"film_titanic_1997", title:"Titanic", type:"Film", year:1997 },
    { id:"film_goodfellas_1990", title:"Goodfellas", type:"Film", year:1990 },
    { id:"film_big_lebowski_1998", title:"The Big Lebowski", type:"Film", year:1998 },
    { id:"film_whiplash_2014", title:"Whiplash", type:"Film", year:2014 },
    { id:"film_la_la_land_2016", title:"La La Land", type:"Film", year:2016 },
    { id:"tv_simpsons_1989", title:"The Simpsons", type:"TV", year:1989 },
    { id:"tv_frasier_1993", title:"Frasier", type:"TV", year:1993 },
    { id:"tv_buff_y_1997", title:"Buffy the Vampire Slayer", type:"TV", year:1997 },
    { id:"tv_sex_city_1998", title:"Sex and the City", type:"TV", year:1998 },
    { id:"tv_six_feet_under_2001", title:"Six Feet Under", type:"TV", year:2001 },
    { id:"tv_arrested_dev_2003", title:"Arrested Development", type:"TV", year:2003 },
    { id:"tv_black_mirror_2011", title:"Black Mirror", type:"TV", year:2011 },
    { id:"tv_crown_2016", title:"The Crown", type:"TV", year:2016 },
    { id:"book_foundation_1951", title:"Foundation", type:"Book", year:1951 },
    { id:"book_catch22_1961", title:"Catch-22", type:"Book", year:1961 },
    { id:"book_clockwork_orange_1962", title:"A Clockwork Orange", type:"Book", year:1962 },
    { id:"book_jurassic_park_1990", title:"Jurassic Park (Book)", type:"Book", year:1990 },
    { id:"book_game_thrones_1996", title:"A Game of Thrones", type:"Book", year:1996 },
    { id:"book_life_pi_2001", title:"Life of Pi", type:"Book", year:2001 },
    { id:"book_da_vinci_code_2003", title:"The Da Vinci Code", type:"Book", year:2003 },
    { id:"book_road_2006", title:"The Road", type:"Book", year:2006 },
    { id:"book_ready_player_one_2011", title:"Ready Player One", type:"Book", year:2011 }
,
    { id:"film_sound_of_music_1965", title:"The Sound of Music", type:"Film", year:1965 },
    { id:"film_mary_poppins_1964", title:"Mary Poppins", type:"Film", year:1964 },
    { id:"film_grease_1978", title:"Grease", type:"Film", year:1978 },
    { id:"film_terms_of_endearment_1983", title:"Terms of Endearment", type:"Film", year:1983 },
    { id:"film_kramer_vs_kramer_1979", title:"Kramer vs. Kramer", type:"Film", year:1979 },
    { id:"film_rain_man_1988", title:"Rain Man", type:"Film", year:1988 },
    { id:"film_sleepless_in_seattle_1993", title:"Sleepless in Seattle", type:"Film", year:1993 },
    { id:"film_youve_got_mail_1998", title:"You've Got Mail", type:"Film", year:1998 },
    { id:"film_love_actually_2003", title:"Love Actually", type:"Film", year:2003 },
    { id:"film_my_big_fat_greek_wedding_2002", title:"My Big Fat Greek Wedding", type:"Film", year:2002 },
    { id:"film_moonlight_2016", title:"Moonlight", type:"Film", year:2016 },
    { id:"film_little_women_2019", title:"Little Women", type:"Film", year:2019 },
    { id:"film_nomadland_2020", title:"Nomadland", type:"Film", year:2020 },
    { id:"film_everything_everywhere_2022", title:"Everything Everywhere All at Once", type:"Film", year:2022 },
    { id:"tv_golden_girls_1985", title:"The Golden Girls", type:"TV", year:1985 },
    { id:"tv_gilmore_girls_2000", title:"Gilmore Girls", type:"TV", year:2000 },
    { id:"tv_desperate_housewives_2004", title:"Desperate Housewives", type:"TV", year:2004 },
    { id:"tv_big_little_lies_2017", title:"Big Little Lies (TV)", type:"TV", year:2017 },
    { id:"tv_this_is_us_2016", title:"This Is Us", type:"TV", year:2016 },
    { id:"tv_the_good_place_2016", title:"The Good Place", type:"TV", year:2016 },
    { id:"tv_the_white_lotus_2021", title:"The White Lotus", type:"TV", year:2021 },
    { id:"tv_the_marvelous_mrs_maisel_2017", title:"The Marvelous Mrs. Maisel", type:"TV", year:2017 },
    { id:"book_eat_pray_love_2006", title:"Eat, Pray, Love", type:"Book", year:2006 },
    { id:"book_where_crawdads_sing_2018", title:"Where the Crawdads Sing", type:"Book", year:2018 },
    { id:"book_little_fires_everywhere_2017", title:"Little Fires Everywhere", type:"Book", year:2017 },
    { id:"book_big_little_lies_2014", title:"Big Little Lies (Book)", type:"Book", year:2014 },
    { id:"book_normal_people_2018", title:"Normal People (Book)", type:"Book", year:2018 },
    { id:"book_circe_2018", title:"Circe", type:"Book", year:2018 },
    { id:"book_song_of_achilles_2011", title:"The Song of Achilles", type:"Book", year:2011 }
,
    { id:"film_west_side_story_1961", title:"West Side Story", type:"Film", year:1961 },
    { id:"film_fiddler_roof_1971", title:"Fiddler on the Roof", type:"Film", year:1971 },
    { id:"film_annie_hall_1977", title:"Annie Hall", type:"Film", year:1977 },
    { id:"film_the_color_purple_1985", title:"The Color Purple", type:"Film", year:1985 },
    { id:"film_working_girl_1988", title:"Working Girl", type:"Film", year:1988 },
    { id:"film_dead_poets_society_1989", title:"Dead Poets Society", type:"Film", year:1989 },
    { id:"film_fried_green_tomatoes_1991", title:"Fried Green Tomatoes", type:"Film", year:1991 },
    { id:"film_four_weddings_funeral_1994", title:"Four Weddings and a Funeral", type:"Film", year:1994 },
    { id:"film_the_english_patient_1996", title:"The English Patient", type:"Film", year:1996 },
    { id:"film_as_good_as_it_gets_1997", title:"As Good as It Gets", type:"Film", year:1997 },
    { id:"film_chocolat_2000", title:"Chocolat", type:"Film", year:2000 },
    { id:"film_billy_elliot_2000", title:"Billy Elliot", type:"Film", year:2000 },
    { id:"film_the_hours_2002", title:"The Hours", type:"Film", year:2002 },
    { id:"film_eternal_sunshine_2004", title:"Eternal Sunshine of the Spotless Mind", type:"Film", year:2004 },
    { id:"film_the_piano_1993", title:"The Piano", type:"Film", year:1993 },
    { id:"film_juno_2007", title:"Juno", type:"Film", year:2007 },
    { id:"film_the_reader_2008", title:"The Reader", type:"Film", year:2008 },
    { id:"film_black_swan_2010", title:"Black Swan", type:"Film", year:2010 },
    { id:"film_the_shape_of_water_2017", title:"The Shape of Water", type:"Film", year:2017 },
    { id:"film_coda_2021", title:"CODA", type:"Film", year:2021 },
    { id:"tv_the_nanny_1993", title:"The Nanny", type:"TV", year:1993 },
    { id:"tv_felicity_1998", title:"Felicity", type:"TV", year:1998 },
    { id:"tv_veronica_mars_2004", title:"Veronica Mars", type:"TV", year:2004 },
    { id:"tv_scandal_2012", title:"Scandal", type:"TV", year:2012 },
    { id:"tv_the_americans_2013", title:"The Americans", type:"TV", year:2013 },
    { id:"tv_outlander_2014", title:"Outlander", type:"TV", year:2014 },
    { id:"tv_shameless_2011", title:"Shameless", type:"TV", year:2011 },
    { id:"tv_normal_people_2020", title:"Normal People (TV)", type:"TV", year:2020 },
    { id:"tv_and_just_like_that_2021", title:"And Just Like That...", type:"TV", year:2021 },
    { id:"book_bridges_madison_county_1992", title:"The Bridges of Madison County", type:"Book", year:1992 },
    { id:"book_secret_life_bees_2001", title:"The Secret Life of Bees", type:"Book", year:2001 },
    { id:"book_time_travelers_wife_2003", title:"The Time Traveler's Wife", type:"Book", year:2003 },
    { id:"book_kite_runner_2003", title:"The Kite Runner", type:"Book", year:2003 },
    { id:"book_lovely_bones_2002", title:"The Lovely Bones", type:"Book", year:2002 },
    { id:"book_help_2009", title:"The Help", type:"Book", year:2009 },
    { id:"book_goldfinch_2013", title:"The Goldfinch", type:"Book", year:2013 },
    { id:"book_station_eleven_2014", title:"Station Eleven", type:"Book", year:2014 },
    { id:"book_night_circus_2011", title:"The Night Circus", type:"Book", year:2011 }
];

  return film.concat(tv).concat(book);

})();
